---
abstract: 'OSX driver for Sys::Info'
author:
  - 'Burak Gursoy <burak@cpan.org>'
build_requires:
  Test::More: 0.40
  Test::Sys::Info: 0.20
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Info-Driver-OSX
no_index:
  directory:
    - monolithic_version
    - builder
    - t
provides:
  Sys::Info::Driver::OSX:
    file: lib/Sys/Info/Driver/OSX.pm
    version: 0.7952
  Sys::Info::Driver::OSX::Device:
    file: lib/Sys/Info/Driver/OSX/Device.pm
    version: 0.7952
  Sys::Info::Driver::OSX::Device::CPU:
    file: lib/Sys/Info/Driver/OSX/Device/CPU.pm
    version: 0.7952
  Sys::Info::Driver::OSX::OS:
    file: lib/Sys/Info/Driver/OSX/OS.pm
    version: 0.7952
requires:
  Capture::Tiny: 0
  Mac::PropertyList: 0
  Sys::Info::Base: 0.78
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-sys-info-driver-osx/
version: 0.7952
